### PR TITLE
Add argument `log`

### PR DESCRIPTION
**Pull request by etiennebacher**
As I said in #4, I'm not an expert with base R plots but it seems to work fine:

``` r
library(plot2)

# from ?plot.default
lx <- seq(1, 5, length.out = 41)
yl <- expression(e^{-frac(1,2) * {log[10](x)}^2})
y <- exp(-.5*lx^2)

plot(10^lx, y, log = "xy", type = "l", col = "purple",
     main = "Log-Log plot", ylab = yl, xlab = "x")
```

``` r

plot2(10^lx, y, log = "xy", type = "l", col = "purple",
     main = "Log-Log plot", ylab = yl, xlab = "x")
```

### CODE REVIEW

**Comment by grantmcdermott** [comment]
Excellent! Let's see how the tests shake out. (There's a bit of a tricky situation in that we need the plots to have been generated from a Linux instance, which you hopefully are.)

Could I also request an extra test using a logged axis (axes) and the `by` (or `|`) argument? Just want to make sure there isn't some unexpected interaction with grouped plots.

**Comment by etiennebacher** [comment]
> Looks like you need to update the docs (devtools::document() or similar).

Ah right, thanks

> from a Linux instance, which you hopefully are.

Yes I have Ubuntu 22.10

> Could I also request an extra test using a logged axis (axes) and the by (or |) argument?

Hum turns out it's trickier than I thought. I can't even put two `plot2()` side-by-side. I'll have a look tomorrow but feel free to jump into this one if you have time ;)

**Comment by grantmcdermott** [comment]
> Hum turns out it's trickier than I thought. I can't even put two plot2() side-by-side.

That's an internal restriction. We can't use `mfrow` on grouped plot2's, because we need to alter the `par`'s internally for legend adjustment etc. I'm hoping to fix/accommodate this in a future iteration. But for now, just feel free to test a single grouped plot a la `plot2(log(Temp) ~ Day | Month, airquality)`.

**Comment by grantmcdermott** [comment]
Closes #15.

**Comment by grantmcdermott** [comment]
Will add another test separately. Thanks @etiennebacher!

**Pull request merged**
