### PR TITLE
docsify

### PR DESCRIPTION
**Pull request by vincentarelbundock**
I have worked a lot on `altdoc`. It still has a few rough corners, but I've already moved all of my packages over and it looks great.

Here is what the `plot2` could look like: 

https://arelbundock.com/plot2

You'll notice that:

* Examples are evaluated and displayed in both the README and the MAN pages.
*  Unlike MkDocs, the Docsify documentation generation framework does not require additional dependencies on the dev machine. It just loads some javascript from the web.
* I changed almost nothing to the `plot2` documentation itself:
  - Fixed a typo in `plot2.Rd`.
  - Removed a `dev.off()` call which broke sequential plots in Rmarkdown.
  - Changed the headers in NEWS for better display.
  - Changed the path where README files are saved to `man/figures/README/`

Also, this is a pure **default** website. The only `altdoc` specific commands I ran were:

```r
library(altdoc)
setup_docs("docsify")
render_docs()
```

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Last note, this is using the Dev version of `altdoc`, which is completely different from the original version. The website shows the current workflow:

https://altdoc.etiennebacher.com

**Comment by vincentarelbundock** [comment]
Yeah, I think we can merge now. I split the examples into a Get Started vignette.

The basic workflow will certainly remain the same, and only some minor behind the scenes stuff should change, requiring very little adaptation here.

We may need to think about a strategy if you want a Github Actions to auto-deploy, and also if you want the separate vignette to be available on both CRAN and website (I have not fully solved that yet, but it should be easy).

For now, all you'll need to do is go to the repo settings to setup Github-Pages. It's very easy. Just do the same thing I do on countrycode. See screenshot:

Screenshot 2023-11-27 165027

**Comment by zeileis** [comment]
Wow, this looks really cool, I look forward to trying it out myself for some of my other packages.

**Comment by vincentarelbundock** [comment]
Glad to hear!

Maybe wait a few weeks, though . I mostly did this here as part of dogfooding process. It's not *quite* ready for public use yet.

**Comment by grantmcdermott** [comment]
Okay, awesome. Please go ahead and merge when you're happy @vincentarelbundock.

I've got a PR in the works to supports faceting (#79) and once that's done then I think we can put out a new release with the shiny new website 🚀

**Pull request merged**
