### PR TITLE
update color reference from arXiv to The R Journal

### PR DESCRIPTION
**Pull request by zeileis**
Grant @grantmcdermott , just a mini-update in response to <https://fosstodon.org/@devSJR/111838661757048332>. Do you prefer if I send you such modifications as PRs or should I merge myself (or commit directly in main)?

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Grant can say what workflow he prefers, but this is trivial so I feel I can just review and merge now.

**Comment by grantmcdermott** [comment]
Thanks, folks.

To Vincent's point. You should both definitely feel empowered to merge PRs, including your own, that you believe are simple and ready (i.e., pass all tests). For the bigger changes, I'd prefer us to have at least one other person review and I'd obviously like to be tagged in all the design-based changes.

(We can revisit a more formal process once the package hits CRAN. But I feel comfortable that we can just rely on individual judgment 'til then.)

**Comment by zeileis** [comment]
Thanks for the explanation, Grant! That's perfect and works very well for me.
I definitely agree that bigger changes should be discussed first and wouldn't merge anything without tagging you first. It was really just about small typos and updates and stuff like that.

**Comment by grantmcdermott** [comment]
Super.

Seeing as we're talking PRs... Just a HU that I'd like to resolve the package name issue (#22 ) as the priority for the next release, since that would obviously be a breaking change if we do proceed. I'll try to summarise my thoughts in the relevant thread when I get a sec and then we can look to make a final call by the end of this week or the next.

**Pull request merged**
