### PR TITLE
 Fix y-title for function names 

### LINKED ISSUE #47: y-title for function names
Compare:

``` r
set.seed(42)
plot(rnorm(1))
```

``` r

library(plot2)
set.seed(42)
plot2(rnorm(1))
```

<sup>Created on 2023-07-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by etiennebacher**
Same as #51, close #47

Much better like this @grantmcdermott

### CODE REVIEW

**Comment by etiennebacher** [comment]
What? No idea why it fails now

**Comment by grantmcdermott** [comment]
Super, thanks. I'll take a look on my local Linux machine as soon as the kids get to school.

**Comment by grantmcdermott** [comment]
Hmmm. It looks like the Hershey font tests (and one par restore test) are triggering the CI errors. It's almost certainly nothing to do with this PR, but I'd like to test a bit more locally. I have to jump on some other work first, but will circle back to this later.

**Comment by etiennebacher** [comment]
This is only on R-devel, could it be due to a recent commit there? For example https://github.com/wch/r-source/commit/fa69bab0e61ceca6d186afe7c91f2d2b558db718?

**Comment by grantmcdermott** [comment]
> This fails only on R-devel, could it be due to a recent commit there? 

Thanks, I think that must be it. I downloaded the action artifact here and manually inspected the `_tinysnapshot_review` diffs. I honestly can't see what the difference is.... maybe some incredibly slight shading/alpha change? I'll wait for R 4.4.0 to re-generate these snapshots locally

At any rate, happy to accept the PR now. Thanks for the contribution @etiennebacher !

**Pull request merged**
